// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upo.FileCenter.EntityFrameworkCore;

namespace FileCenter.Tools.SchemaMigrations.Migrations.FileCenterDb
{
    [DbContext(typeof(FileCenterDbContext))]
    [Migration("20190614165029_InitialFileCenterDbContextMigration")]
    partial class InitialFileCenterDbContextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Upo.FileCenter.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("DeleteTime");

                    b.Property<long>("DownloadTimes");

                    b.Property<string>("Extensions");

                    b.Property<string>("FileName");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrivate");

                    b.Property<long>("Length");

                    b.Property<string>("PhysicalPath");

                    b.Property<DateTime>("UploadTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
